### PR TITLE
More Turnitin additions (and minor fix)

### PR DESCRIPTION
**Pull request by benchen71**
Minor fix in timeaccesschart.php is checking for no students enrolled in course and exiting if none.
(So sorry, but looking at my changes below, it seems I have inadvertently reverted some of your whitespace changes.  I hope that isn't a major problem!)

### CODE REVIEW

**Comment by marceloschmitt** [comment]
Ok, Ben. I am just making the code error free when someone test it with codechecker. As soon as I finish it, I will make this version the production version.

**Comment by benchen71** [comment]
Sounds great!  I have no more changes at the moment.

**Comment by marceloschmitt** [comment]
Ben, I have made your changes manually. I will close your request. Please test it.

**Comment by benchen71** [comment]
Hi Marcelo,

I made some minor changes to lib.php and made a pull request.

Sincerely,
 Ben.

**Pull request closed without merging**
