### PR TITLE
Issue#54 Add new capabilities

### PR DESCRIPTION
**Pull request by TomoTsuyuki**
For #54

### CODE REVIEW

**Comment by marceloschmitt** [comment]
I am sorry. I will do that. I will need 3 weeks, probably. Now I am in the middle of a flood. It will take 10 days for the waters to go down: https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.estadao.com.br%2Fsustentabilidade%2Fchuvas-porto-alegre-rio-grande-do-sul%2F&psig=AOvVaw1XZM4Nxtm1Y-zFdXtVfO9X&ust=1715169335990000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCPDtl-29-4UDFQAAAAAdAAAAABAJ

**Comment by dmitriim** [comment]
Hi @marceloschmitt any chance you can have a look at this PR? We have just rebased it on top of the recent changes.

**Comment by marceloschmitt** [comment]
Ok Dmitri. Taking a look now. I have changed a function in lib not to get suspended students in a course. But I will see your proposal.

**Comment by marceloschmitt** [comment]
I have merged what you asked.

**Pull request merged**
