### PR TITLE
Issue #1 Fix some group by statements for Postgres

### PR DESCRIPTION
**Pull request by danmarsden**

### CODE REVIEW

**Comment by marceloschmitt** [comment]
I am going to test it, today.

**Comment by marceloschmitt** [comment]
I think I will have to rethink the query. If I have something like:

## x   y  z

1  2  3
2  2  3
3  2  5

And use something like GROUP BY x, y, z; I will have 3 rows. They will not be grouped because x is different for every row. That is the reason why timecreated was not int group by clause. And timecreated was not in select also. It was in a formula that produces day. That is the problem of the inner select.

In the outer select, the same problem will happen with id. Id is used because get_records_sql demands a unique key as the first field. So, probably the best solution is something like:
LEFT JOIN {user} usr ON usr.id = log.userid

Probably, I need another solution.

**Comment by marceloschmitt** [comment]
I suppose this may solve the problems. It is an example without variables. 

SELECT temp2.userid+(week_1000000) as id, temp2.userid, firstname, lastname, email, week, number, numberofpageviews
    FROM (  
        SELECT temp.userid, week, COUNT(_) as number, SUM(numberofpageviews) as numberofpageviews
                FROM (
                        SELECT MIN(log.id) as id, log.userid,
                            FLOOR((log.timecreated + 1407121200)/ 86400)   as day,
                            FLOOR( (((log.timecreated  + 1407121200) / 86400) - (1407121200/86400))/7) as week,
                            COUNT(*) as numberofpageviews
                        FROM mdl_logstore_standard_log as log  
                    WHERE courseid = 2245 AND action = 'viewed' AND target = 'course' AND log.timecreated >= 1407121200
                        GROUP BY userid, day, week
                        ) as temp
                GROUP BY week, temp.userid
        ) as temp2
        LEFT JOIN mdl_user usr ON usr.id = temp2.userid
                ORDER BY LOWER(firstname), LOWER(lastname),userid, week

**Comment by danmarsden** [comment]
Cool - couple of typos there - COUNT() I think is supposed to be COUNT(id) and temp2.userid+(week1000000) I think is supposed to be temp2.userid+(1000000)

after those 2 changes the sql runs fine in my postgres database (It doesn't return any results but that's probably because my main db doesn't have much real data in it)

**Comment by marceloschmitt** [comment]
I will adjust the other query and will send you the right syntax. You will be able to test them.

**Comment by marceloschmitt** [comment]
I will adjust the other query and will send you the right syntax. You will be able to test them.

**Comment by marceloschmitt** [comment]
Well. The queries are probably ready.  If I copy here, some symbols desappear.

**Pull request closed without merging**
